services:
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-server
    ports:
      - "5002:5002"  
    env_file: ./.env
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - bot-server


networks:
  bot-server:
    driver: bridge