export const keywords = {
  shopNameKeywords: [
    "name",
    "shop name",
    "দোকানের নাম",
    "What's your shop name?",
    "Tell me the name of your shop",
    "What is this shop called?",
    "Can I know your shop name?",
    "Shop name please",
    "Send your store name",
    "Name of your page?",
    "Business name?",
    "Store title?",
    "What is your business called?",

    // More English (real phrasing)
    "What do you call your store?",
    "What's your brand name?",
    "What is the page name?",
    "What's the business name?",
    "I want to know the shop name",
    "Page er name ta bolen",
    "Please share your store name",
    "Name of your business please",
    "Brand name ki?",
    "Your shop title?",

    // Banglish (Romanized Bangla)
    "shop er nam ta ki?",
    "apnar dokaner nam ki?",
    "shop ta ki nam e?",
    "dokan er name bolen",
    "brand er nam ki?",
    "page er nam ki?",
    "shop name ta den",
    "nam ta bolben?",
    "shop ta nam ki?",
    "business er nam ki?",

    // More Banglish
    "dokan ta ki name cholche?",
    "store er nam ta janaben?",
    "nam ta dite parben?",
    "shop er title ta ki?",
    "apnader page er nam ki?",
    "shop ta kon name e ache?",
    "nam janaiyen plz",
    "shop ta ki name famous?",
    "shop er nam jante chai",
    "dokan er title ta ki?",

    // বাংলা (Bangla script)
    "দোকানের নাম কী?",
    "আপনার দোকানের নাম কী?",
    "আপনার দোকানের নাম বলুন",
    "শপের নাম কী?",
    "বিজনেসের নাম জানাবেন?",
    "আপনার শপের নাম বলবেন?",
    "শপের নামটা জানাতে পারেন?",
    "আপনার ব্র্যান্ডের নাম কী?",
    "দোকানের নাম জানতে চাই",
    "নামটা বলবেন প্লিজ?",
  ],

  shopAddressesKeywords: [
    "address",
    "location",
    "ঠিকানা",
    // English
    "address",
    "shop address",
    "your address please",
    "where is your shop?",
    "what's the location?",
    "send me the address",
    "store location",
    "business address",
    "where are you located?",
    "give me your location",

    // More English (natural queries)
    "shop location please",
    "where is your store?",
    "can you share address?",
    "location of the page",
    "how do I reach you?",
    "your store address?",
    "full address please",
    "where to find you?",
    "I need the address",
    "where is the business? ",

    // Banglish (Romanized Bangla)
    "address ta den",
    "shop er address ta bolen",
    "apnar dokaner thikana ki?",
    "location ta janaben?",
    "shop koi?",
    "dokan ta koi ache?",
    "kothay shop ta?",
    "apnader location ki?",
    "store er location den",
    "dokan ta kothay?",

    // More Banglish
    "dokan koi ache?",
    "location janate parben?",
    "apnader thikana bolben?",
    "store koi?",
    "shop er location ta ki?",
    "dokan er address ta din",
    "page er address ki?",
    "shop ta koi ache bolen",
    "kothai pabo apnader?",
    "address janaben?",

    // বাংলা (Bangla script)
    "ঠিকানা",
    "দোকানের ঠিকানা",
    "আপনার ঠিকানা কী?",
    "দোকান কোথায়?",
    "লোকেশন দিন",
    "আপনার দোকান কোথায়?",
    "আপনাদের দোকান কোথায়?",
    "আপনার দোকানের ঠিকানা বলুন",
    "দোকানটা কোথায়?",
    "ঠিকানাটা জানাবেন?",
  ],

  shopPhoneKeyword: [
    // English
    "phone",
    "phone number",
    "contact",
    "contact number",
    "mobile",
    "mobile number",
    "your number",
    "can I get your number?",
    "give me your phone number",
    "how can I call you?",
    "contact info",
    "business number",
    "store contact",
    "customer care number",
    "calling number",
    "phone number please",
    "shop phone",
    "phone pls",
    "whatsapp number",
    "can I contact you?",

    // Banglish (written in English letters)
    "apnar number ta ki?",
    "phone number den",
    "contact number janaben?",
    "mobile number den",
    "dokan er number ta bolen",
    "shop er contact number ki?",
    "apnader sathe contact korbo kivabe?",
    "number ta chai",
    "call korar number den",
    "number ta janaiyen",

    // More Banglish
    "contact info chai",
    "apnader number ta dite paren?",
    "phone ta din",
    "number please",
    "kivabe contact korbo?",
    "mobile er number ki?",
    "customer service number bolben?",
    "shop number ta ki?",
    "kothay call korbo?",
    "phone number chai",

    // বাংলা (Bangla script)
    "ফোন",
    "মোবাইল",
    "ফোন নম্বর",
    "মোবাইল নম্বর",
    "যোগাযোগ নম্বর",
    "আপনার নম্বর কী?",
    "ফোন নাম্বার দিন",
    "আমি কীভাবে আপনাদের ফোন করব?",
    "দোকানের নম্বর দিন",
    "যোগাযোগের তথ্য দিন",
  ],

  shopCategoryKeywords: [
    // English
    "category",
    "categories",
    "type",
    "product type",
    "shop type",
    "business category",
    "store category",
    "what type of products?",
    "what's your category?",
    "kind of products?",
    "item type",
    "your niche",
    "product category",
    "business type",
    "shop niche",
    "what do you sell?",
    "nature of your shop",
    "type of business",
    "what kind of items?",
    "what sort of products?",

    // Banglish (written in English letters)
    "ki dhoroner products?",
    "dokan er category ki?",
    "business er type ta ki?",
    "kon dhoroner jinis bikri koren?",
    "shop ta ki dhoroner?",
    "category bolen",
    "ki niye shop?",
    "product er category janaiyen",
    "shop er dhoron ki?",
    "kichu category janaben?",

    // More Banglish
    "business ta kon niche e?",
    "shop ta kon type er?",
    "category ta bolben?",
    "product type bolen",
    "kon niche e kaj koren?",
    "apnar shop er jinispotro kon dhoroner?",
    "apnar shop er product gulo kon category r?",
    "category chai",
    "shop er jinisgulo ki type er?",
    "ki ki category ase?",

    // বাংলা (Bangla script)
    "ধরন",
    "ক্যাটাগরি",
    "কোন ধরণের পণ্য?",
    "আপনার ব্যবসার ধরন কী?",
    "আপনার দোকানের পণ্যের ধরন কী?",
    "পণ্যের প্রকারভেদ",
    "আপনার দোকা‌নের ক্যাটাগরি বলুন",
    "আপনার দোকান কী ধরনের জিনিস বিক্রি করে?",
    "আপনার দোকান কোন ক্যাটাগরিতে পড়ে?",
    "আপনার দোকানের ধরন কী?",
  ],

  shopAllInfoKeywords: [
    // English
    "shop info",
    "shop information",
    "shop details",
    "shop data",
    "about shop",
    "about your shop",
    "tell me about your shop",
    "what is your shop",
    "what do you sell",
    "describe your shop",
    "business details",
    "business info",
    "business information",
    "about your business",
    "page info",
    "page information",
    "page details",
    "facebook page info",
    "facebook page details",
    "shop profile",
    "about this page",
    "store information",
    "tell me about the store",
    "what is this page about",
    "describe the page",
    "details of your page",
    "introduction of your shop",
    "company profile",
    "brand info",
    "brand details",
    "seller info",
    "who are you",
    "who owns this page",
    "who runs this shop",
    "who are you people",
    "what do you do",
    "your business details",
    "full shop details",
    "store info",
    "store profile",
    "give shop details",
    "i want to know about your shop",
    "can you tell me about your page",
    "please share your shop info",
    "who is the owner",
    "what products do you sell",
    "summary of your shop",
    "store background",
    "basic info",
    "overview of the shop",
    "info about your service",
    "page introduction",
    "what does this page do",
    "business overview",
    "page background",
    "intro of your shop",
    "info about your company",
    "facebook shop info",

    // Bangla (Phonetically written for matching)
    "dokaner tottho",
    "dokaner somporke bolo",
    "apnar dokan ki",
    "dokan somporke bolen",
    "shop somporke bolen",
    "apnar page er tottho",
    "page er tottho",
    "page ki niye",
    "ei page ta ki niye",
    "shop ki niye",
    "ki bechen",
    "ki bikri hoy",
    "page somporke",
    "shop er name ki",
    "shop er background",
    "shop ki service dei",
    "ki ki pawa jai",
    "shop er introduction",
    "shop er profile",
    "shop er overview",
    "company er tottho",
    "business er tottho",
    "ei business ta ki",
    "apnar business ki",
    "dokan somporkito tottho",
    "page er somporke bolo",
    "facebook page ki niye",
    "brand er somporke",
    "dokan er full details",
    "business er kotha bolo",
    "dokan er khobor dao",
    "shop er bivaroni dao",
    "dokan ki dhoroner",
    "shop er dhoron ki",
    "dokan kon category",
    "category bolen",
    "kon dhoroner product bechen",
    "shop er service",
    "business er background",
    "company profile chai",
    "dokan ki dhoroner",
    "page ki kaj kore",
    "page ta ki kaj kore",
    "dokan niye kichu bolo",
    "facebook dokan somporke",
    "business plan ki",
    "brand er tottho chai",
    "dokan er job details",
    "apnar kaj ki",
    "apni ki koren",
    "shop er kaj ki",
    "business ke chalay",
    "shop ke chalay",
    // General inquiries about shop/page
    "দোকান সম্পর্কে বলো",
    "আপনার দোকান সম্পর্কে জানাতে পারবেন?",
    "দোকানটা কী ধরনের?",
    "আপনার দোকান কি বিক্রি করে?",
    "আপনার দোকান কিসের?",
    "দোকানের বিস্তারিত বলুন",
    "দোকানের তথ্য দিন",
    "আপনার ব্যবসা সম্পর্কে বলুন",
    "এই পেজটা কী সম্পর্কে?",
    "আপনার পেজ সম্পর্কে বিস্তারিত বলুন",
    "এই ফেসবুক পেজটা কেন?",
    "এই পেজের কাজ কী?",
    "এই পেজটি কী করে?",
    "পেজের বিবরণ দিন",
    "আপনার ব্যবসার বিবরণ দিন",
    "আপনার সার্ভিস কী?",
    "আপনার পণ্য কি কি?",
    "আপনার দোকানের পরিচিতি দিন",
    "দোকানের সম্পর্কে একটু বলবেন?",
    "এই দোকানটা কী করে?",
    "পেজ সম্পর্কে জানতে চাই",
    "আপনার কোম্পানি সম্পর্কে বলুন",
    "আপনার ব্র্যান্ড সম্পর্কে বলুন",
    "এই ব্র্যান্ডটা কী?",
    "আপনার ব্যবসা কবে শুরু হয়েছে?",
    "এই পেজটা কে চালায়?",
    "পেজের মালিক কে?",
    "আপনি কে?",
    "আপনার দোকান কোথায় অবস্থিত?",
    "আপনারা কোথা থেকে পরিচালিত হন?",
    "দোকানের ঠিকানা কী?",
    "ফোন নাম্বার কী?",
    "দোকানের ফোন নাম্বার দিন",
    "কেনাকাটার নিয়ম বলুন",
    "কীভাবে অর্ডার করবো?",
    "আপনাদের সম্পর্কে জানতে চাই",
    "আপনার সম্পর্কে বলুন",
    "দোকানটা সম্পর্কে একটু বলুন",
    "আপনারা কিভাবে কাজ করেন?",
    "আপনার সার্ভিস এর ধরন কী?",
    "এই পেজের মালিকানা কার?",
    "পেজের কাজ কী?",
    "আপনার দোকানে কী কী পাওয়া যায়?",
    "কী ধরনের পণ্য বিক্রি করেন?",
    "আপনার দোকানে কী বিক্রি হয়?",
    "আপনার কোম্পানির নাম কী?",
    "বিজনেস সম্পর্কে তথ্য দিন",
    "আপনাদের সম্পর্কে কিছু বলুন",
    "এই শপ সম্পর্কে জানাতে পারেন?",
    "দোকানের পরিচয় দিন",
    "দোকানের বর্ণনা দিন",
    "আপনার প্রতিষ্ঠানের সম্পর্কে বলুন",
    "এই পেজটা কেন খুলেছেন?",
    "আপনার কাজ কী?",
    "এই ব্যবসার ধরন কী?",
    "আপনার দোকানের সারাংশ দিন",
    "ব্যবসা শুরু কবে?",
    "শপ এর ব্যাকগ্রাউন্ড কী?",
    "পেজে কী পাওয়া যাবে?",
    "আপনারা কীভাবে সাপোর্ট দেন?",
    "আপনারা কাদের জন্য কাজ করেন?",
    "কী ধরনের গ্রাহকদের জন্য?",
    "আপনাদের সার্ভিস এলাকা কোথায়?",
    "আপনারা হোম ডেলিভারি দেন?",
    "আপনারা কীভাবে কাজ করেন?",
    "আপনাদের নিয়ম কী?",
    "আপনাদের টার্গেট গ্রাহক কারা?",
    "আপনার শপের মূল উদ্দেশ্য কী?",
    "এই দোকানের লক্ষ্য কী?",
    "আপনাদের ভিশন কী?",
    "মিশন কী?",
    "আপনাদের প্রোফাইল দিন",
    "আপনার ব্যবসার প্রোফাইল দিন",
    "আপনার কোম্পানি প্রোফাইল",
    "এই শপ কীভাবে শুরু হয়েছে?",
    "আপনার দোকান কতদিন চলছে?",
    "আপনার দোকানের নাম কী?",
    "পেজের নাম কী?",
    "আপনার দোকানের ক্যাটাগরি কী?",
    "আপনারা কোন ক্যাটাগরিতে কাজ করেন?",
    "আপনাদের মূল পণ্য কী?",
    "এই পেজে কী বিক্রি হয়?",
    "আপনার ব্র্যান্ডের বর্ণনা দিন",
    "আপনার প্রোডাক্ট নিয়ে কিছু বলুন",
    "আপনার সার্ভিস সম্পর্কে বিস্তারিত বলুন",
    "কীভাবে সাপোর্ট পাবো?",
    "এই পেজে অর্ডার কিভাবে করবো?",
    "আপনারা কাস্টমার কিভাবে হ্যান্ডেল করেন?",
    "আপনারা কী ধরণের কাস্টমার সার্ভিস দেন?",
    "আপনাদের কন্টাক্ট ডিটেইলস দিন",
    "দোকানের পরিচয় জানতে চাই",
    "পেজের বিস্তারিত জানতে চাই",
    "আপনার ব্যবসার উদ্দেশ্য কী?",
    "এই শপ কী অফার করে?",
    "দোকান সম্পর্কে কিছু জানাতে পারেন?",
  ],

  shopAllProductKeyword: [
    // English
    "all",
    "all products",
    "all items",
    "product list",
    "item list",
    "show all",
    "full list",
    "all available products",
    "all available items",
    "see all products",
    "list of products",
    "what do you sell?",
    "everything you sell",
    "show me all products",
    "show full list",
    "show everything",
    "display all items",
    "I want to see all products",
    "complete product list",
    "total items",

    // Banglish (written in English letters)
    "sob product",
    "sob item",
    "sob ponno",
    "sob kichu dekhte chai",
    "all product gulo koi?",
    "all item bolo",
    "shop er sob product dekhai",
    "ponno gulo dekhai",
    "sob jinis list dao",
    "ki ki sell koren?",

    // More Banglish
    "shob product list chai",
    "product list den",
    "shop er sob kichu dekhte chai",
    "product er shorol talika chai",
    "shop e ki ki ache?",
    "dokan e jeta jeta ache",
    "total product gulo bolo",
    "shop er sob dekhbo",
    "ponno gulo kothai?",
    "show sob kichu",

    // বাংলা (Bangla script)
    "সব",
    "সব পণ্য",
    "সব প্রোডাক্ট",
    "সকল পণ্য",
    "সকল প্রোডাক্ট",
    "পণ্যের তালিকা",
    "সব কিছু দেখান",
    "সব দেখাও",
    "সব পণ্য চাই",
    "আমি সব প্রোডাক্ট দেখতে চাই",
  ],
};
