name: Deploy with Docker Compose

on:
  push:
    branches:
      - main 
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event_name == 'push' || (github.event.pull_request.merged == true)
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Stop existing containers
        run: docker compose down || true

      - name: Rebuild and restart containers
        run: docker compose up -d --build

      - name: Cleanup unused images
        run: docker system prune -f
