name: Hex-Bot CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  run-and-deploy:
    runs-on: hex-machine
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Install dependencies
        run: npm install
      
      - name: Deploy & restart app
        run: |
          ls -a
          pm2 status
          pm2 delete hex-bot || true
          pm2 start npm --name "hex-bot" -- run start:dev
